= Tornium

A third party, integrated informational website with Discord bot functionality, dedicated to simplifying the playing of https://www.torn.com[Torn City]. Developed and maintained by tiksan.

== Tornium Features
- Faction banking with real time faction balance and a system to ping faction bankers for withdrawl requests.
- OD detection notifications
- Stat database with ability to query based on stat range
- Chain list generator, with query for "fair fight" ratio adjustment

== Tornium Discord Bot Features (via discord command)
- Retaliation notifications
- Organized crimes (OCs) ready notifications and delayed notifications including the who and why reasoning for the delay
- Stakeout functionality
- Faction vault balance check
- Faction banking withdrawls, and the ability to cancel banking requests
- Ability to see which faction members are online/offline/hospital/or inactive for a variable amount of days (I.E 2+ days)
- User verification with functionality to match users/nicknames to thier torn profiles and ID's
- Discord-based stock verification and notifications

== Installation
Not yet supported.

=== Optional packages
Tornium can be run without all of the below optional packages, but will auto-detect installation and run with those packages if they are installed.

 - ddtrace - for monitoring of the flask and celery instances
 - orjson - for increased performance in encoding and decoding of JSON in all API calls

== Tornium Extensions
Tornium partially supports extensions for new Discord commands and new Flask endpoints (with no support for Celery tasks currently). However, over-writing pre-existing commands and endpoints is not supported. A template for Tornium extensions can be found at https://github.com/dssecret/tornium-extension-template[dssecret/tornium-extension-template]. Extensions automatically install into Tornium upon start up of Tornium with auto-detection of extensions (must start with `tornium-`). For more information or if you find any issues, please open an issue in either repository.

NOTE: Tornium extensions must be released as open source code under a GPLv3 or another GPL license due to the restrictions of the https://github.com/dssecret/tornium-pro/blob/master/LICENSE[tornium-pro license]. For more details, take a look at https://www.gnu.org/licenses/gpl-3.0.en.html[GPL website].

== License
https://github.com/dssecret/tornium-pro/blob/master/LICENSE[AGPLv3]

== Release Notes
This project follows https://semver.org/[semver v2.0] so all bug fixes, breaking changes, features, etc. can be found in the https://github.com/dssecret/tornium-pro/blob/master/CHANGELOG.adoc[changelog].

== Contact
- tiksan on Discord at tiksan(hastag)9110
- tiksan on Torn at https://www.torn.com/profiles.php?XID=2383326[tiksan [2383326\]]
